# pull latest versions from git
if [[ ! -d $HOME/.updates ]]
then
   git clone https://github.com/rbmv/xarxes-lab.git $HOME/.updates
else
   cd $HOME/.updates && git pull
   cd -
fi

# create UAB specific environment
if [[ ! -d $HOME/.uab-env ]]
then
  mkdir $HOME/.uab-env
fi

# create bin directory for custom tools
if [[ ! -d $HOME/.tools ]]
then 
  mkdir $HOME/.tools
fi

#update UAB enviornment
rsync -a $HOME/.updates/bash-env/* $HOME/.uab-env/

#update simulation scripts
rsync -a $HOME/.updates/simulation-scripts/* $HOME/practiques/practica1/simulation-scripts 

#update tools 
rsync -a --exclude 'sendRawEth' $HOME/.updates/tools/bin/* $HOME/.tools/

# update bash_profile
cp $HOME/.updates/bash-env/user-specific/bash_profile $HOME/.bash_profile

# launch fortune qotd server - do this as a proper service next year
$HOME/.tools/fortune-server.sh 2>/dev/null &
